# Generated by Django 4.0.3 on 2022-06-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_tomeet_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('done_for_today', models.CharField(max_length=200)),
                ('important', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
